apiVersion: v1
kind: Service
metadata:
  name: evolve-rtice-assessment-service
spec:
  selector:
    app: evolve-rtice-assessment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
  type: ClusterIP
